# Generated by Django 5.2.4 on 2025-08-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
