# Generated by Django 5.2.4 on 2025-08-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_alter_invoice_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file_path',
            field=models.FilePathField(blank=True, path='bills'),
        ),
    ]
