# Generated by Django 5.2.4 on 2025-08-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_invoice_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
