# Generated by Django 5.2.4 on 2025-09-16 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255)),
                ('machine_type', models.CharField(choices=[('PHOTOCOPIER', 'Photocopier'), ('PRINTER_LASER', 'Laser Printer'), ('PRINTER_INKJET', 'Inkjet Printer'), ('MFD', 'Multifunction Device'), ('SCANNER', 'Scanner'), ('FAX', 'Fax Machine'), ('PART', 'Machine Part'), ('TONER', 'Toner Cartridge'), ('INK', 'Ink Cartridge'), ('RIBBON', 'Ribbon'), ('PAPER', 'Paper Tray')], max_length=50)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField()),
                ('copy_counter', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_service', models.DateField()),
                ('note', models.TextField()),
                ('serviceman_name', models.CharField(blank=True, max_length=255)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_notes', to='billapp.machines')),
            ],
            options={
                'ordering': ['-date_of_service'],
            },
        ),
    ]
