# Generated by Django 5.2.4 on 2025-09-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0007_machines_servicenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenote',
            name='fee_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
