# Generated by Django 5.2.4 on 2025-09-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0008_servicenote_fee_charged'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenote',
            name='copy_counter_at_service',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
