# Generated by Django 5.2.4 on 2025-09-19 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0009_servicenote_copy_counter_at_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicenote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='servicenote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
