# Generated by Django 5.2.4 on 2025-09-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0010_alter_servicenote_options_servicenote_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], max_length=10, null=True),
        ),
    ]
