# Generated by Django 5.2.4 on 2025-09-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0013_alter_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='machine_type',
            field=models.CharField(choices=[('PHOTOCOPIER', 'Photocopier'), ('PRINTER_LASER', 'Laser Printer'), ('PRINTER_INKJET', 'Inkjet Printer'), ('MFD', 'Multifunction Device'), ('SCANNER', 'Scanner'), ('FAX', 'Fax Machine')], max_length=50),
        ),
    ]
